// Couleurs globales de l'app
export const C = {
  dark:   '#0B0D17',
  card:   '#111827',
  card2:  '#1A2233',
  red:    '#FF4D2E',
  white:  '#F8FAFC',
  muted:  'rgba(255,255,255,0.4)',
  border: 'rgba(255,255,255,0.08)',
  green:  '#10B981',
  gold:   '#F59E0B',
}

// Styles partagés
export const S = {
  screen: {
    minHeight: '100vh',
    background: C.dark,
    fontFamily: "'Outfit', sans-serif",
    color: C.white,
    overflowX: 'hidden',
  },
  nav: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '18px 22px 0',
  },
  content: {
    padding: '28px 22px 100px',
  },
  title: {
    fontFamily: "'Syne', sans-serif",
    fontSize: 32,
    fontWeight: 800,
    lineHeight: 1.1,
    color: C.white,
    marginBottom: 8,
    letterSpacing: '-0.02em',
  },
  subtitle: {
    fontSize: 14,
    color: C.muted,
    marginBottom: 28,
    lineHeight: 1.65,
    fontWeight: 300,
  },
  input: {
    width: '100%',
    background: C.card,
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    padding: '14px 16px',
    fontSize: 14,
    color: C.white,
    fontFamily: "'Outfit', sans-serif",
    outline: 'none',
    marginBottom: 14,
  },
  label: {
    fontSize: 10,
    fontWeight: 600,
    color: 'rgba(255,255,255,0.35)',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    marginBottom: 7,
    display: 'block',
  },
  btnMain: {
    width: '100%',
    padding: '17px',
    background: C.red,
    border: 'none',
    borderRadius: 16,
    color: C.white,
    fontSize: 15,
    fontWeight: 700,
    fontFamily: "'Outfit', sans-serif",
    cursor: 'pointer',
    boxShadow: '0 8px 32px rgba(255,77,46,0.3)',
    marginBottom: 12,
  },
  btnSec: {
    width: '100%',
    padding: '17px',
    background: 'transparent',
    border: `1px solid ${C.border}`,
    borderRadius: 16,
    color: 'rgba(255,255,255,0.5)',
    fontSize: 14,
    fontFamily: "'Outfit', sans-serif",
    cursor: 'pointer',
  },
  bottomBar: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    padding: '16px 22px',
    background: 'rgba(11,13,23,0.95)',
    backdropFilter: 'blur(12px)',
    borderTop: `1px solid ${C.border}`,
    zIndex: 100,
  },
  logoSq: {
    width: 36,
    height: 36,
    borderRadius: 10,
    background: C.red,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 17,
    fontWeight: 800,
    color: C.white,
    boxShadow: '0 4px 14px rgba(255,77,46,0.5)',
  },
}
